spring:
  activemq:
    broker-url: tcp://localhost:61616
    password: admin
    user: admin
server:
  port : 8081
queue:
  jsonReader: activemq:JSONReader.queue
  fixedLengthReader: fixedLengthReader.queue
  
  
